#!/bin/bash
SAXON="./bin/saxon/saxon-he-12.5.jar"
BASEX="./bin/basex/bin/basex"
PUBLISH="./lib/xq/publish.xq"
XSL_RESUME="./lib/xsl/resume.xsl"
XML_RESUME="./xml/resume.xml"
DIR_HTML="./tmp/html"
DIR_XML="./tmp/xml"
FILE_BIB="./bib/bibliography.bib"
GITHUB_ATOM="https://github.com/ilmari-koria/website/commits.atom"

# retrieve github atom feed
wget -O "$DIR_XML/github/github.atom" $GITHUB_ATOM

# Generate bib
# TODO generate bib xml with xquery
bibtex2html --style "ieeetr" --footer "" --header "" --no-header --nodoc --nobibsource --ignore-errors --sort-as-bibtex --output $DIR_XML/bibliography/bibliography $FILE_BIB
tidy -q --numeric-entities yes -asxhtml -o $DIR_XML/bibliography/bibliography.xml $DIR_XML/bibliography/bibliography.html

# call stylesheet transformations
$BASEX $PUBLISH

# css
cp ./css/style.css ./tmp/html/style.css

#resume
# TODO mv this to main publish query
java -cp $SAXON net.sf.saxon.Transform  -t -s:"$XML_RESUME" -xsl:"$XSL_RESUME" -o:"$DIR_HTML/ilmari-koria-resume.tex"
pdflatex -output-directory $DIR_HTML "$DIR_HTML/ilmari-koria-resume.tex"
rm $DIR_HTML/*.log $DIR_HTML/*.tex $DIR_HTML/*.aux $DIR_HTML/*.out   
