:PROPERTIES:
:ID:       11b5081b-0b43-4beb-8820-dd9e6a1f9d75
:END:
#+title: Sounding the Dharma of Insentient Beings: Soundscape Composition and Zen Buddhism
#+filetags: zen soundscape-composition buddhism
#+description: Discussion on soundscape composition and Chan studies.
#+date: 2023-03-27

#+begin_verse
溪聲便是廣長舌，
山色豈非清淨身。
夜來八萬四千偈，
他日如何舉似人？
#+end_verse

#+begin_verse
The sound of the stream is his long, broad tongue;
The mountain form, his immaculate body.
This evening's eighty-four thousand verses —
How will I tell them tomorrow?[fn:1]
#+end_verse
-- Su Shi 蘇軾 (1037-1101 CE)

* Introduction
What do mountains and rivers have to say to us, and how do we listen? A persisting interest in my studies of Zen has been the concept of the inanimate preaching buddha-dharma (/wuqing shuofa/ 無情說法). Attributed to the Tang Chinese Zen master Nanyang Huizhong 南陽慧忠 (675-775 CE), the above expression points to an understanding that equates the fabric of reality with enlightenment itself [[cite:ShiGuoJingFoJiaoWuQingShuoFaDeXueLiTanJiu2017][cite:ShiGuoJingFoJiaoWuQingShuoFaDeXueLiTanJiu2017]]. The underlying ontology of /wuqing shuofa/ is one in which all participants exist in an interdependent nexus of causes and conditions. By extension of this logic, mountains, trees and rivers constantly communicate transcendental truths (their intrinsic buddhahood), insights one can appreciate through attentive listening. In light of our current environmental crises, such affective "resources" are crucial to contemplate in our efforts to reassess our relationships with the environment. This post freely explores the above notions in light of soundscape composition, a range of creative approaches for engaging with our acoustic environments. And suggests that the above methods offer theoretically and methodologically mature strategies for deepening our awareness and relationship with the non-human world.

* Background: From Huizhong to Dōgen
The conceptual background of wuqing shuofa is not without debate, developing in tandem with the movement of Buddhist ideas from India to China [[cite:ShiGuoJingFoJiaoWuQingShuoFaDeXueLiTanJiu2017][cite:ShiGuoJingFoJiaoWuQingShuoFaDeXueLiTanJiu2017]]. Within this lineage of ideas, wuqing shuofa cannot be separated from the question of whether insentient beings possess buddha-nature[fn:2] or not. The conventional use of the above term can be traced to the /Mahāparinirvāṇasūtra/ (/Dabanniepan jing/ 大般涅槃經) that emphasises the universality of buddha-nature among sentient beings. The preaching of grasses and trees 草木 or ‘earth, trees, tiles and rocks’ 土木瓦石 developed out of later commentarial traditions that sought to extend buddha-nature to the insentient world as well. For Huizhong, a proponent of the latter, the ‘mind of the ancient Buddha’ 古佛心 was nothing more than ‘wall and tile rubble’ 牆壁瓦礫 ([[http://tripitaka.cbeta.org/T47n1986B_001#0519b18][CBETA T.1986B:0519b18]][fn:3]). The whole universe is itself the buddha's body, with all it's constituents constantly expressing this reality. These "voices" can, subsequently, trigger spiritual insight if approached with a non-discriminating and non-dualistic mind. Such discussions would see development in the later Caodong Chan School 曹洞宗 (Jp., Sōtō-shū) and in Japan, notably by Dōgen 道元 (1200-1253).

* Background: Dōgen 2                                                :ignore:
In his reading of the /Dabanniepan jing/, Dōgen suggests buddha-nature transcends sentient beings, being an inherent characteristic of the universe. Writing in his work /Keisei sanshoku/ 谿声山色, Dōgen comments upon the above poem by Su Shi regarding an experience of hearing a stream as the preaching of a buddha. The poet reveals buddha-nature within the phenomenal or conventional world but laments how he could share this spiritual vision [[cite:bielefeldtTreasuryTrueDharma2013][cite:bielefeldtTreasuryTrueDharma2013]]. Dōgen suggests that such experiences should be approached like a koan-riddle (/gongan/ 公案), a spiritual tool for (sentient) beings to probe reality. While Dōgen was adamant about the universality of buddha-nature, he emphasised the subtlety of understanding truths heard in the environment. In his work titled /Mujō seppō/ 無情說法 (i.e. /wuqing shuofa/), the meditation master emphasises the need to contextualise the preaching of insentient beings as part of the fundamental activity of enlightenment-in-action [[cite:bielefeldtTreasuryEyeTrue2009][cite:bielefeldtTreasuryEyeTrue2009]]. Dōgen's vehicle for this is his complex notion of seated meditation (zazen/zuochan 坐禪), which points to the practice of actualised enlightenment in our phenomenal world. A banal interpretation of the above is that one should approach environmental phenomena with curiosity and spiritual doubt about one's place as part of the bigger picture.

* On Soundscape Composition
Jumping now to the contemporary era, the term "soundscape composition" emerged out of the intellectual movements following the World Soundscape Project (WSP). Beginning in the late 1960s at Simon Fraser University (British Columbia, Canada), the focus of the WSP was to raise awareness and document our changing soundscapes. The above is especially in light of noise pollution, and the rising consciousness towards environmental issues [[cite:truaxGenresTechniquesSoundscape2002][cite:truaxGenresTechniquesSoundscape2002]] [[cite:westerkampLinkingSoundscapeComposition2002][cite:truaxGenresTechniquesSoundscape2002]]. Out of the forms of composition that emerged from the WSP, one that included radically altering original recordings, included a neutral documentary-like approach involving minimal compositional interference. As a "phonographic" approach (the auditory equivalent of photography), this involved disseminating environmental sound by framing it for an audience. Both the techniques above, however, aim at pointing directly to the source sounds, seeking to maintain a contextual link with their origins. The above effectively highlights aspects of the soundscape and helps communicate it to others. As a form of listening and composition, it allows us to make sense of unstructured acoustic environmental data and refine it into a more approachable report-like format. The latter is inherently with the purpose of fostering environmental awareness.

* On Soundscape Composition, truax and hildegard                     :ignore:
Soundscape composition cannot be whatever environmental sounds mashed together. As discussed above, soundscape composition should first keep a degree of recognisability of its sounds. The above is so that the listener's memories, associations and recognition of sounds can be invoked. It is important that the listener is aware and also oriented towards what the soundscape composition is about. Soundscape composition needs to, therefore, maintain a sense of structure, narrative and indeed, composition, and avoid becoming an assorted set of "holiday slides" [[cite:dreverSoundscapeCompositionConvergence2002][cite:dreverSoundscapeCompositionConvergence2002]]. The composer's role is to raise awareness and communicate the voice of the world, the soundscape being that which makes environmental issues audible. Following Hildegard Westerkamp, the above approaches establish a forum for artists to address issues in our soundscapes and comment upon them via the compositional method [[cite:westerkampLinkingSoundscapeComposition2002][cite:westerkampLinkingSoundscapeComposition2002]]. In this regard, composition could allow us to create a clearer sense of being and belonging, away from the attempts of aural unconsciousness encouraged by consumer culture. This invitation is not just at the expense of the composers but extends a responsibility to listen deeply to the audience.

* The Zen of Soundscape Composition 
For composers and zen masters, all perspectives of the environment are unique to the perceiver. French composer Luc Ferrari's (1929-2005) genre-defining work /Presque Rien n°1, ou le lever du jour au bord de la mer (1967-1970)/ (1970) is a sonic snapshot of a Yugoslavian village [[cite:ferrariPresqueRienOu2012][cite:ferrariPresqueRienOu2012]] [[cite:dreverSoundscapeCompositionConvergence2002][cite:dreverSoundscapeCompositionConvergence2002]] [[cite:truaxGenresTechniquesSoundscape2002][cite:truaxGenresTechniquesSoundscape2002]]. The work presents highlights of a seamlessly edited field recording from a fixed perspective throughout one day, emphasising the flow and sense of time. The sound events themselves determine the actual compositional structure of the piece, with the composer acting almost as a curator. The above allows the carts, tractor engines and cowbells to effectively speak for themselves, resulting in a soundscape narrative that invites listeners to be inquisitive and discerning. On one level, listeners can distinguish individual sound objects and their relative spatial attributes. And on another lever, listeners can freely mingle in the soundscape, associating any arising thoughts and memories evoked therein. Any knowledge we may "gain" as a result is not, in this sense, necessarily discursive but is more reflexive in nature. 

* Presque Rien; Soundscape Composition and Chan 2; field recording   :ignore:
/Presque Rien n°1/ invites one to be curious about environmental sounds here, understood as having their own agency and provenance. As a composition, the piece helps establish a relationship between these sounds, the composer and the listener. For Dōgen, the non-duality of this relationship is paramount to resolve. From an absolute perspective, there is no separation between us and the landscape, with humans and non-humans intimately connected in a mutually supportive ecology. By extension, there is no clear divide between sentience and non-sentience, being conventional categories we use to function in a phenomenal world. From a strictly zen point of view, what is ultimately preaching is us, sermons flowing out of our own intrinsic buddhahood. In other words, what we are studying and listening to is the self. For the composer and listener, the task is to be aware, which for Dōgen is actualised in zazen practice. Here, zazen is no other than the medium by which the conventional divides between human and non-human is reduced. The spiritual ear required to hear the sermons of tractor engines and wooden carts is enacted in this attentiveness and made more transparent through repeat listening. 

* Conclusion
This blog post sought to share a few thoughts on the relationship between zen practice and soundscape composition. The main takeaway of this exploration is the importance of being inquisitive about the environment, and what environmental sounds are ultimately expressing. The soundscape, and its audible characteristics, are likened here to a /kalyāṇamitra/ (/shanzhishi/ 善知識), a "good friend," a spiritual companion who encourages one to keep practising and keep being focused on the task at hand. Creative compositional choices can subsequently allow us as practitioners to share what insights we have gained with others, thereby acting as interpreters and communicators. The above is with the intention of reducing the ultimately unsatisfactory divides between self/not-self and sentient/insentient. 

[fn:1] Translation by Carl Bielefeldt [[cite:bielefeldtTreasuryTrueDharma2013][cite:bielefeldtTreasuryTrueDharma2013]].

[fn:2] Ch., /foxing/ 佛性; Skt., /buddhadhātu/. The inherent capacity to achieve enlightenment.

[fn:3] See English translation of this work by William Powell [[cite:powellRecordTungshan1986][cite:powellRecordTungshan1986]].








