#+title: Event Report: Sentience Beyond the Human - Session Two 
#+filetags: interspecies-justice Taiwan conference
#+description: Notes on academic workshop.
#+date: 2022-08-15

*Event Title*: /Sentience Beyond the Human/ 多物種感知國際工作坊 (https://clab.org.tw/en/events/sentience-beyond-the-human/)

*Date/Location*: 2022/07/07, Taiwan Contemporary Culture Lab (C-LAB), Taipei 臺灣當代文化實驗場

* Introduction
What does the non-human world have to say to us, and how do we listen? Facing an uncertain future, one situated within an Anthropocene, we must critically examine how we situate ourselves with our earthly co-inhabitants. This involves working with non-anthropocentric viewpoints, and questioning our inherent assumptions of non-human "sentience(s)," in terms of the political, historical, and relational. This event report seeks to offer a succinct account of four different (but interrelated) perspectives, pointing to such more-than-human viewpoints. The talks, presented at a workshop held at the Taiwan Contemporary Culture Lab (C-Lab) 臺灣當代文化實驗場 engage with environmental humanities, animal studies, media, international law, sensory anthropology, and history. And, as the original conference program rightly explains, explore ‘pathways toward ecological togetherness beyond the apocalyptic imagination of Anthropocene futures.’ With this in mind, this work will discuss the talks presented during the latter half of the full-day workshop, introducing their contents and conclusions. Additionally, this piece contains a brief discussion section further summarizing and fleshing out the points made above. Due to space considerations, this report emphasizes some details over others. Therefore, I invite readers to consult the above scholar's published works on the subject.  

* Jeffrey Nicolaisen (Taiwan ICCS, NYCU) -- /Why the Caged Bird Sings: Gallus gallus (the Common Chicken) Helps us to Rethink the Anthropocene/
Environmental humanist Jeffrey Nicolaisen 倪杰 begins the second half of the workshop with a critical discussion of the concept of Anthropocene. He puts forward the central guiding question of his talk, namely what is the story of our current epoch? The speaker looks to nuance current anthropocentric trajectories that underlie discussions of environmental change by introducing the notion of a /Galluscene/. Purported by the Anthropocene Working Group (AWG), a special committee of the International Commission of Stratigraphy (ICS), the Galluscene is marked by a new stratigraphic layer composed of the remains of the common chicken (/Gallus gallus/). As the presenter explains, G. gallus, with a current population of 22.6 billion (2016), makes for a good candidate for such a marker. This is aided by the rapid human-instigated changes in the species since 1945, including human-directed selection, and measurable changes in diet. Nicolaisen highlights the connection between the story of our emerging epoch, and the common chicken, the latter involved with a multitude of aspects in modern history. This includes capitalism, the rise of the sciences, colonialism, and the neo-liberalization of the food industry. The agency of the common chicken is thus contrasted with that of the AWG Anthropocene, one that only recognizes human will.

As Nicolaisen highlights, the AWG suggests the agency of humans on Earth through different bio-systems, such as the Technosphere ("anthroposphere"). This refers to the sum material output of the contemporary human enterprise, reflecting a kind of ’intrinsic’ agency, being autonomous, goal-oriented, and self-organizing. The Technosphere is a result of several strata of theorizing on biospheric development, evolving out of both teleological (/noösphere/, /ecozoic era/) and non-teleological (/Gaia hypothesis/) models. However, Nicolaisen suggests we must move beyond simply human enterprises. He points to the flourishing of different species assemblages, such as G. gallus and humans, locked together in co-evolution. The speaker contrasts the Galluscene with anthropocentric exceptionalism, the latter driven by human-centric ethics, and an emphasis on human agency. This includes the limited scope of the Anthropocene that cannot refer to all humans, due to only five countries producing most of the world’s emissions. The Galluscene can, conversely, provide a sense of multi-species interdependence, pointing to bio-centric ethics, and an understanding of the limits of human agency and human technological drive.

* Tobias Linné (Department of Communication and Media, Lund University) -- /The Emotional Labour of Farmed Animals/
Critical Animal Studies and Media Studies scholar Tobias Linné continues the theme of domesticated animals by discussing the /emotional labor/ of cows in Sweden. As the speaker describes, emotional labor was developed to study the management of emotions by workers in the service industry. However, this category should be considered in the study of animal workers as well, a notion absent from broader discussions of labor. Linné suggests this has been likened to domestic labor and other household work ‘in the shadows.’ The emotional labor of animals is notable in, for example, service animals in health care and the entertainment industry. This includes the visibility of animals in social media and meme culture, which serve to arouse emotional responses in the viewer. As the speaker explains, social media is itself a medium powered by emotions and directly benefiting from the role of animals. With this in mind, the presenter discusses the above points through a case study involving two social media accounts set up by Swedish farmers. These forms of opinion building in Swedish agriculture are becoming more visible, with personal accounts posting about their work and the animals they work with.

Situated within critical animal studies, Tobias Linné seeks to understand how these farmers are presenting their animals in media and what aspects are publicly disclosed. A major narrative of these accounts is the close relationship between the farmer and the natural world, termed here as inter-species intimacy and care. In this sense, these accounts emphasize the daily work of caring for these animals, showcasing their quality of life, and the human-animal relationships therein. Another theme is one that seeks to blur the boundaries between human and non-human. Animals are presented as having individual life stories and personality traits, that result in a superficial agency, history, and free will. Posts describe cows being dressed up, and farmers speaking through the animals, making it seem that the cow is communicating with the viewer. While these accounts play with the boundaries between human and animal, the cows lack full personhood, being relegated as quasi-subjects, akin to pets. These anthropomorphized depictions overwrite any real agency the animal has, thus tacitly reinforcing human-animal boundaries, downplaying any potential ethical conflicts on farms. Through this, the presenter suggests that these cows are performing emotional labor for the agricultural industry by alleviating consumer anxieties. Ultimately these are business accounts intended to bolster capital accumulation, with the emotional qualities of cows exploited as part of affective/emotional capitalism.
* Chung-Hsien Lee 李仲軒 (Institute of Asia and Pacific Studies, Taiwan Sun Yat-sen University) -- /Constructing A New Climate Regime in Court?/
The third talk was presented by Legal scholar Chung-Hsien Lee 李仲軒, which shared the results of current investigations (and thoughts) into climate change litigation. The speaker bases his discussion on the results of the recent /The State of the Netherlands vs. Urgenda Foundation/ (2019), held as a paradigm shift in climate change law. Here, the Supreme Court of the Netherlands upheld previous findings that the State of the Netherlands is legally obliged to reduce its greenhouse gas emissions. This is by a minimum of 25 percent by the end of 2020. As Lee explains, this decision is the first of its kind, in which a state is ordered to develop a more robust climate change agenda. The talk highlighted the problematic language used in the proceedings, suggesting that the conservative nature of legal institutions may hamper the development of efficient environmental law. Lee suggests, that these movements should also extend to current legal discourses in climate change to involve the rights of non-humans as well. In this regard, the law has to have other roles to play in the age of the Anthropocene, requiring a shift of present legal paradigms. These are instigated by ever harsher climate realities, challenging courts to confront issues beyond the scope of conventional litigation.

As discussed above, the speaker argues that current legal paradigms, (and the doctrines therein) constitute obstacles to climate change mitigation. These involve, for example, the /political question doctrine/, and the /standing to sue doctrine/. The latter points to the adversity of courts towards politically charged issues, and the former to the legal requirements of a plaintiff to proceed with legal action. The talk highlighted the importance of the “perceived” neutrality of the court, one that employs the power of science to determine causation. Results must be value-free and in the binary, allowing for no gray areas to make a fair judgment. The legal system is, therefore, a culprit in maintaining an air of perfect science and democracy, enabling people to view it as entirely mechanical and predictable. However, as Lee explains, when confronting issues related to climate change, these structures are beginning to show their limits. Alternative legal paradigms are needed to overcome the limitations of relying only on scientific insights to determine climate-related causation and the lack of international political consensus. This includes reassessing the assumed neutrality of court proceedings and confronting biases within the legal system that actively reshape facts (and values) in accordance there-in. In this regard, the speaker highlights the importance of welcoming alternative voices and sources, to create more adaptable litigation when confronting the complexities of climate change.

* I-Yi Hsieh 謝一誼 (Taiwan ICCS, NYCU) -- /I Hear You: Animal Soul Statues in Taiwan/
The closing talk of the workshop was held by anthropologist I-Yi Hsieh 謝一誼, presenting an ethnographic analysis of animal soul statues (/chuhun bei/ 畜魂碑) in Taiwan. Most of the statues in question were built and associated with slaughterhouses during the Japanese colonial era in Taiwan (1895-1945). The speaker argues that these efforts point to popular recognition of the sentience of non-human animals during this period. Slaughterhouses are, in this sense, arenas where such recognition is forged and maintained, provoked by hearing the cries of butchered animals. The speaker juxtaposes these themes against the early colonial efforts in Taiwan to develop civil hygiene infrastructure, funded by regulated hog slaughter taxation. She acknowledges the importance of recent drives within environmental humanities for scholars to pursue approaches that are attentive to such highly interrelated (“entangled”) processes of life. Through the function of ’multispecies co-becoming,’ the speaker looks to articulate the kinds of human-animal relations in colonial Taiwan, and how the historical emergence of hog sentience can be used to understand an urban ontology that still shapes how human-animal relations are understood today. Within this, the speaker stresses the importance of the place of coloniality in the discussion of non-human sentiences, and multispecies relationality within the Anthropocene.

Hsieh describes the origins of the statues, recounting the development of public slaughterhouses that followed the ban on private slaughter during early Japanese colonial rule. The speaker moves on to describe the contents inscribed on the statues, that point to the motivations for erecting such commemorative monuments. As discussed above, this involves reactions to ’hearing the porcine cries’ by those living in sonic proximity to the slaughterhouses. The butchering sessions usually started at 2-3 am, suggesting that the sonic intensity of “invisible” howling hogs may have lead to distinct sensory events. The novelty of public slaughterhouse soundscapes in early colonial Taiwan thus led to a new kind of multispecies relationality, historically granting the possibility of ascribing sentience to hogs. The speaker suggests that in the mutual confrontation towards animal suffering, the colonial government and its citizens were able to move toward unifying distinct multispecies worlds. The presenter moves to reflect on what it means to hear the cries of suffering animals and the politics of such sensory engagement. Hsieh then ties the above case with the contemporary meat industry and calls for critical relational perspectives for examining modern human-porcine ontologies. 

* Discussion
During the 20-minute discussion at the end of the workshop, several key points were expanded upon, a few of which I have summarized below. I-Yi Hsieh began this section by further elaborating on the soul statues, sharing their material qualities and provenance, being made of larger three-meter stones, but without figurative qualities. Today some of these statues are associated with animal worship. Following this, Tobias Linné further discussed the nature of social media use among Swedish farmers, and how widespread this phenomenon is. Although these are farms that have grown in recent years, part of the motivation for social media use is to “give an air” of a smaller scale. Linné’s talk sparked further reflections on the anthropomorphizing of animals, with the presenter pointing out the potential for critical anthropomorphism in the context of representation. These discussions included widening the concept of labor in animals beyond the emotional to what, for example, Jeffrey Nicolaisen highlighted as “metabolic labor.”

Lastly, a question was posed to the presenters which sought to inquire on three different themes in the workshop, namely personhood, agency, and the senses. And, how these perspectives relate to and converge among the different scholars' research. Jeffrey Nicolaisen suggested that to tie these three themes together, one needs to consider welfare. As he points out, the legal concept of “person” should not always be equated to “human,” with personhood being affixed to a multitude of different entities (e.g. corporations and organizations). Using metabolic labor as an example, Nicolaisen proposes that agency is not limited to simple goal-directed behavior. Rather, this should involve adding to the notion of subjectivity the possibility to feel, thus linking to the senses. Through this process, we can slowly begin to appreciate welfare, and thereafter begin to build a more equitable notion of personhood. In the last 30 seconds, Chung-Hsien Lee concludes the discussion by reflecting on his approach utilizing systems theory, and how the above categories can ultimately converge and be reconciled.

* Conclusion and Acknowledgments
This report sought to share notes on four talks presented at C-Lab that discussed different stances on themes revolved around notion of Anthropocene. While not able to share all details of complex and multifaceted projects, this work is nevertheless hoped to invite more interest into the research of the above scholars. The author of this work would like to thank Derek Sheridan (Institute of Ethnology, Academia Sinica) for moderating this part of the workshop, and Owen Raymond for his vital technical assistance throughout the event. And lastly, C-Lab and NYCU for their support in leading-edge Arts & Humanities scholarship.

* Disclaimer
All content above reflects the author's reflections and judgements, and should not be taken for an authoritative account of the works of the above scholars

