#+title: Event Report: Jeffrey Nicolaisen - Inequality of Equalities
#+filetags: interspecies-justice Taiwan conference
#+description: Report on academic talk in environmental humanities.
#+date: 2022-06-05

*Talk Title*: 平等間的不平等：台灣漢族佛教徒與泰雅族獵人之間（不）可通約的存有論協商 Inequality of Equalities: The Negotiation of the (In)Commensurable Ontologies of Han Buddhists and Atayal Hunters in Taiwan

*Date/Location*: 2022/04/13, National Yang Ming Chiao Tung University (Hsinchu, Taiwan)

* Introduction
In our current state of environmental change and decline in species diversity worldwide, we must re-contextualise our relationships with our surroundings and co-inhabitants. Within this lies the need to interrogate existing cultural constructions of "equality" that permeate law, religion and politics, especially considering the interests of non-human animals. Presenting at National Yang Ming Chiao Tung University 國立陽明交通大學 (Hsinchu, Taiwan), environmental humanist Jeffrey Nicolaisen 倪杰 suggests alternatives to positions regarding animal rights and the equality of species. Through multi-disciplinary efforts intersecting religious studies, law and ethnography, he firstly demonstrates the plurality of attitudes towards inter-species relations in Taiwan. He then suggests adopting an "equality of life" 生命平等, as an alternative to current anthropocentrisms, based on Western legal standards and liberal humanism. Rich in analysis and detail, the talk situates itself at the centre of discussions surrounding our current global ecological disaster. And offers viable alternative future pathways that take into account the well-being of all life on Earth. This event report seeks to firstly present a succinct account of the talk in question, describing its contents and conclusions with broad detail. Additionally, this work contains a brief discussion and question section further summarising and fleshing out the points made above. Due to space considerations, this report emphasises some details over others. Therefore, I invite readers to consult the pre-recorded lectures in [[https://www.youtube.com/watch?v=hMUo1PS1PIQ][Mandarin]] and [[https://www.youtube.com/watch?v=LY9afNm2Cac][English]], and Jeffrey Nicolaisen's published works on the subject. 

* Lecture Notes - Introduction
As highlighted above, Jeffrey Nicolaisen based his discussion on ethnography and the critical reading of works intersecting law, Buddhist studies, indigenous studies and history. His research firstly pertains to the Buddhist animal protection organisation, Life Conservationist Association 關懷生命協會. Secondly, he presents findings from indigenous Christian Tayal 泰雅族 communities in Jianshi Township, emphasising their quasi-legal framework of the /gaga/. In the first part of the talk Nicolaisen establishes the basic research question, namely what is equality? He does this through analysing two different categories of equality, namely the conventional notion of human equality 人人平等, and the equality of life 生命平等. Nicolaisen conducts his discussion via ontological analysis, concentrating on four key points. He does this by firstly horizontally situating the relevant intellectual and cultural movements at play, namely Christianity, Buddhism, Liberalism, and the gaga. Secondly, the researcher seeks to challenge the applicability of the conventional categories of nature 自然 and religion 宗教 in terms of traditional Chinese religions. He then further seeks to consider how current legal definitions of religion, and the separation of church and state, serve to actually suppress non-theistic traditions. Lastly, Nicolaisen discusses alternative frameworks for Western liberalism in the context of the equality of life.

* On Equality
By the normative notion of equality, Nicolaisen refers to the work of Enlightenment thinker John Locke (1632-1704). As he explains, it is Locke's /Natural Rights/, and the universal equality between people, that remains the basis for legal definitions of equality today. Citing legal scholar Jeremy Waldron (1953-), the speaker suggests how few people today would question the justifications for this formulation of equality. This concept, however, relies on Christian ethical and intellectual foundations to be applicable, with equality being something guaranteed by a Christian formulation of God. Non-Christians do not have, as Locke would understand it, the capacity to know either God, or the values bestowed by God for humanity. Turning to Buddhism, the notion of an /equality of life/ points to a much older Asian notion of equality. This is in turn promoted in Taiwan by the Buddhist nun and Religious studies professor, Shih Chao-hwei 釋昭慧 (1957-) and her co-founded Life Conservationist Association 關懷生命協會. This approach to equality is one that is less anthropocentric, not differentiating between the human and animal domains. Her approach does not only concern the protection of non-human animals, but also addresses issues specific to the human realm, such as same-sex rights, nuclear power, etc. With this in mind, Buddhist sources can provide alternative frameworks to human/non-human equality, one that stresses equal kindness to all sentient beings.

* The /Gaga/
After establishing the theoretical foundations for his discussion, Nicolaisen turns to explicating the ethnographic aspects of his work. The supporting data for his discussion come from the remote Tayal mountain hamlet of Tbhahu (Tianpu) 田埔部落, in Hsinchu, Northern Taiwan. Of primary interest here is the gaga ("law") of the Tayal, originally referring to head-hunting, but today replaced by the hunting of non-human animals. As an activity guided by gaga, hunting follows internal regulatory measures for sustainable practices, including believed moral rewards for successfully hunts. In terms of equality and the gaga, there are differing interpretations, for example, concerning the status of non-human animals in the Tayal afterlife. This includes views in which human and non-human animals become bonded through the act of hunting, whereby both parties can crossover to the afterlife. As Nicolaisen explains, this interpretation suggests a form of equality, with non-human animals also carrying an (immortal) soul. One can find other interpretations that point to an equality of life in contemporary Tayal publications and media. For example, in the 2019 film /Rainbow Judgement/, based on Tayal author Rimuy Aki's 里慕伊．阿紀 (1962-) book of the same name, suggests an equality based on killing. In this context, the Tayal are to respect all life that is apart from their own and subject to hunting practices.

* Regarding Hunting Law
The speaker then turns to discussing contemporary legal problems regarding inter-species and ethnic relations in Taiwan. He highlights issues revolving around the popular religious practice of the "release of life" 放生, and the legality of Tayal hunting. Issues concerning the release of life point to the haphazard setting free of certain animals, some unsuited for the Taiwanese environment. This includes instances whereby, for example, the Buddhist Chinese Life Protection Association 中華護生協會 set free poisonous snakes into inhabited regions, both indigenous and non-indigenous. While historically associated with Buddhism, many Buddhists in Taiwan today, including Shih Chao-hwei, oppose release of life ceremonies. The nun points to the fact that followers of popular religion, including some nominally Buddhist and Daoist groups, have a utilitarian view of this practice. In this regard, these groups believe such rituals can increase one's positive karma, at the unwitting expense of mistreating non-human subjects. Christian indigenous groups see these ceremonies as incursions and attempts at Han ‘multi-species’ colonisation, that threaten community integrity and general well-being. There are no specific provisions for release of life rituals in Taiwanese law, further aggravating the sense of encroachment felt by the Tayal. 

Early Taiwanese hunting law since the 1970's, while intending to preserve declining populations of native species, however, included prohibitions inadvertently targeting indigenous hunting practices. As Nicolaisen explains, legal efforts to regulate wildlife in Taiwan carry the Lockean formulation of equality, which only takes into account human needs. Non-human animals are subsequently relegated as resources or commodities. Buddhist organisations backed these movements as they inadvertently connoted a decrease of non-violence towards animals, further solidifying colonising sentiments by indigenous hunter groups. To address this, indigenous groups lobbied the international community, with recognition gained in the 2007 UN Declaration on the Rights of Indigenous Peoples (UNDRIP). Furthermore, the domestic Indigenous Peoples Basic Law 原住民基本法 (2005) legalised the hunting of wild animals in the context of traditional culture and sustenance. However, hunting practices are at odds with efforts by conservationist organisations, notably the Life Conservationist Association (LCA) 關懷生命協會 and the Eco-Conservation Alliance (ECA) 生態保育聯盟. The LCA/ECA 1994 draft of the Wildlife Conservation Act have come into conflict with the Indigenous Peoples Basic Law, with determination's favoured towards the former. As Nicolaisen concludes, while centred on non-human animals, the discussions above still reflect human biases, with the needs of animals ignored.
* Conclusion
In conclusion, the ecological policy of the different players above is fundamentally determined by human rights, based on the Lockean concept of human equality. There is no consideration of the interests of non-human animals, with ecological discussions framed in terms of Western liberalism and the current overarching hegemonic system. However, the notion of an equality of life presents an alternative to these prevailing world views. Although Buddhist thinking prohibits killing, and the gaga (according to contemporary readings) characterises itself by hunting, both take into consideration the *interests of non-humans.* However, the concept of the gaga and Buddhist nonviolence, struggle to gain recognition because of the current emphasis on human equality. To overcome this, Buddhists (represented by Shih Chao-hwei) seek to align themselves with secular and international organisations. This includes allying with contemporary thinkers on animal rights, such as utilitarian philosopher and professor of Bioethics, Peter Singer (1946-). Nicolaisen argues that this is to establish a sense of "secular" legitimacy as a movement in the face of established organisations such as the LCA. In this regard, the speaker suggests compromises between Tayal and Buddhists, involving recognition of opposing stances on the issue. Furthermore, this includes ways to introduce any overlap between ontologies, to question the prevailing idea of human equality based ecological thinking.

* Discussion and Questions
After the presentation by Jeffrey Nicolaisen, the participants asked several insightful questions. I have selected and summarised three below, and invited readers to also consult the pre-recorded lectures for the expanded discussion.

** On Buddhist Cosmology                                          
The first question revolved around Buddhist cosmology, and the concept of transmigration in the six levels of /saṃsāric/ existence 輪迴. The question sought to reconcile the apparent contradiction between equality and the different levels of (seemingly) hierarchical existence in Buddhist thought. In approaching this question, the speaker adopted Waldron's reading of John Rawls' (1921-2002) concept of ‘range property’. This points to the idea that beyond a threshold all are equal within a certain range. Here, for example, Locke's range property for all humans is that we possess rationality and virtue. However, not all humans are equal in terms of genetics, educational background, environmental factors, etc. In terms of Shih Chao-hwei, her range property for all beings (within saṃsāra) is that they are equally sentient, subject to dependant arising 緣起, and able to become buddhas. This pragmatic response indicates that when arbitrating between the equality of two sentient beings, one must ask how close is this animal to Buddhahood? As Nicolaisen highlights, a "sage" is always closer to Buddhahood over an endangered snake. However, one who is closer to Buddhahood is also more ethical, which takes priority when dealing with, for example, the protection of said endangered snake.  

** The Teleology of Buddhism and Peter Singer
The second discussion point further dealt with the utilitarian aspects of Shih Chao-hwei's approach to equality. The question highlighted the seeming elite status of those more capable of (or closer to) Buddhahood, as beings who are perhaps more "equal" than others. The danger is to prefer those who further along the Buddhist path, and so a crucial issue is to safeguard the inherent rights of others as well. As Nicolaisen points out, in any system there will inevitably be situations where one has to place the interests of one against another. In confronting this contradiction, the Buddhist's and Tayal have their own answers. For Shih Chao-hwei, one must always try to root these choices in the basic Buddhist assumption of non-harming 不害. However, humans are never fully capable of appreciating all the factors at play when making such decisions, with conflicts of interest always becoming apparent. In this sense, people require some hierarchy, with Shih Chao-hwei, for example, suggesting we look at which party is closer to potentially achieving Buddhahood. Nicolaisen also highlights the thought of Singer who suggests that all parties are equal because they feel and have sentience.  However, Singer opposes blanket animal rights, preferring a softer form of equality that takes into account the /interests/ of said party. However, both Singer and Shih Chao-hwei would always choose the human over the poisonous snake. Taking into account range property, we do not have to think of everything as being part of an undifferentiated whole

** Regarding Law and Ontology
The last discussion involved taking into account the ramifications for Taiwanese law in considering the different ontologies among Taiwanese indigenous groups. As discussed above, the presenter begins with treating all ontologies at play on equal grounding. However, in Taiwan liberalism is the basis for law which, while constitutionally protecting indigenous culture, does not recognise their legal systems. If a legal establishment were to, however, graft these ontologies onto conventional legal structures, this could allow for an expanded vocabulary to deal with, for example, animal rights. This could then potentially give non-human animals (and nature itself), a chance to have a say in legal matters. For example, in release of life ceremonies, freedom of religion would not be able to supersede the inherent rights of the animals in question. As Nicolaisen points out, these notions are part of the worldwide "Rights of Nature movements," which attempts to allocate non-human entities (incl. mountains, rivers or even all of nature) constitutional rights.

* Conclusion
This report sought to share notes on Jeffrey Nicolaisen's talk discussing different stances towards equality as found in Taiwan today. While not able to share all details of a complex and multifaceted project, this work is nevertheless hoped to invite more interest into Nicolaisen's research.
* Disclaimer
All content above reflects the author's reflections and judgements, and should _not be taken_ for an authoritative account of Jeffrey Nicolaisen's scholarly work.
