default-log-level=info
graphviz=/usr/bin/dot
ignore-trailing-whitespace=true
log-levels=CoffeePot:trace,Parser:info
pretty-print=true
progress-bar=tty
normalize-line-endings=true
ignore-bom=true
trailing-newline-on-output=true